### ISSUE TITLE
Newest Version Bug

### ISSUE THREAD

**Issue by GooglyTank** [Zer0-Official/School-Bus-Mate#1]
Hey, the newest version uploaded as of time of posting this. Doesnt work the program opens and closes with little more than a white screen!

**Comment by Zer0-Official** [comment]
Ill take a look

**Comment by Zer0-Official** [comment]
Try downloading again and running `main.py`

**Comment by GooglyTank** [comment]
Yes working now thanks!

**Comment by Zer0-Official** [comment]
Yeah, I think you downloaded it in the updating process so there were some files missing.
